version: '3.9'

services:
  server: 
    build: .
    ports:
      - "3000:3000"
    db:
      image: "postgres"
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "root"